{% set version = "5.7.0dev1" %}
{% set commit = "62badbed3be3f137dde5978279f1a26e52f7cea6" %}
{% set siriusDistName = "sirius_gui_multi_os-sirius" %}

package:
  name: sirius-ms
  version: {{ version }}

source:
  - url: https://github.com/boecker-lab/sirius/archive/{{ commit }}.zip
    sha256: 738d45eb7a22074fb8f64a35f3d8dd7095cb082ff12774b154320eeef1897482

build:
  number: 0
  script_env:
    - siriusDistName={{ siriusDistName }}

requirements:
  build:
    - openjdk
  run:
    - openjdk
    - coin-or-cbc  # [not win]

test:
  requires:
    - wget  # [not win]

about:
  home: https://bio.informatik.uni-jena.de/software/sirius/
  license: AGPL-3.0-only AND OTHER
  license_file:
    - sirius_dist/sirius_gui_multi_os/build/install/{{ siriusDistName }}/COPYING.txt
    - sirius_dist/sirius_gui_multi_os/build/install/{{ siriusDistName }}/LICENSE.txt
    - sirius_dist/sirius_gui_multi_os/build/install/{{ siriusDistName }}/licenses.md
  summary: "SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS"
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other
    small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID
    (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command line version
    of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
